          COPY                    TELAHEAD.CPY.       
          05 LINE  7 COL  2 VALUE
             "N=Novo  B=Buscar  G=Gravar  X=Excluir  E=Sair".   
          05 LINE  8 COL  1 VALUE
             "                                                  ".
          05 LINE  9 COL  1 VALUE " Opção: ".             
          05 LINE 10 COL  1 VALUE
             "                                                  ".             
          05 LINE 11 COL  1 VALUE " -- MANUTENCAO DE ".
          05 LINE 11 COL 19 VALUE (MANUTENCAO).
          05 LINE 12 COL  1 VALUE
             "                                                  ".
          05 LINE 13 COL  1 VALUE
             "--------------------------------------------------".
          05 LINE 14 COL  1 VALUE
             "                                                  ".

